{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "9cd4d9b1-cff1-4888-94f3-d01252b9961e",
   "metadata": {},
   "source": [
    "pip install opencv-python\n",
    "pip install imutils\n",
    "pip install dlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cc42c60f-6401-4b67-b398-a38177cf7537",
   "metadata": {},
   "outputs": [],
   "source": [
    "from imutils.face_utils import FaceAligner, rect_to_bb\n",
    "import imutils\n",
    "import dlib\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "from glob import glob\n",
    "import os\n",
    "import requests\n",
    "\n",
    "from PIL import Image, ImageOps\n",
    "from pillow_heif import register_heif_opener\n",
    "\n",
    "register_heif_opener()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "742562f6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# capture issues to resolve in the future:\n",
    "# buttons as faces\n",
    "# other people\n",
    "capture_issues = ['20210614_183300.jpg', '20210829_093342.jpg',\n",
    "                  '20220301_222916.jpg','20220626_135456.jpg', \n",
    "                  '20220917_163316.jpg', '20220925_190928.jpg',\n",
    "                  '20221128_194535.jpg']\n",
    "\n",
    "\n",
    "\n",
    "need_to_be_renamed = [\n",
    "               '327766_2110888256203_2015606625_o.jpg',\n",
    "               '13483308_10206732714060887_9206378074821374390_o.jpg',\n",
    "               '13938075_10207037654724213_7700935497558972159_o.jpg',\n",
    "                'IMG_2267.JPG',\n",
    "                'AirBrush_20210330203813.jpg']\n",
    "\n",
    "image_issues = capture_issues + need_to_be_renamed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c3dcd7d4-8ea5-4af4-b409-fcaa05ed323a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from imutils.face_utils.helpers import FACIAL_LANDMARKS_68_IDXS\n",
    "from imutils.face_utils.helpers import FACIAL_LANDMARKS_5_IDXS\n",
    "from imutils.face_utils.helpers import shape_to_np\n",
    "import numpy as np\n",
    "import cv2\n",
    "\n",
    "class FaceAligner:\n",
    "\tdef __init__(self, predictor, desiredLeftEye=(0.35, 0.35),\n",
    "\t\tdesiredFaceWidth=256, desiredFaceHeight=None):\n",
    "\t\t# store the facial landmark predictor, desired output left\n",
    "\t\t# eye position, and desired output face width + height\n",
    "\t\tself.predictor = predictor\n",
    "\t\tself.desiredLeftEye = desiredLeftEye\n",
    "\t\tself.desiredFaceWidth = desiredFaceWidth\n",
    "\t\tself.desiredFaceHeight = desiredFaceHeight\n",
    "\n",
    "\t\t# if the desired face height is None, set it to be the\n",
    "\t\t# desired face width (normal behavior)\n",
    "\t\tif self.desiredFaceHeight is None:\n",
    "\t\t\tself.desiredFaceHeight = self.desiredFaceWidth\n",
    "\n",
    "\tdef align(self, image, gray, rect):\n",
    "\t\t# convert the landmark (x, y)-coordinates to a NumPy array\n",
    "\t\tshape = self.predictor(gray, rect)\n",
    "\t\tshape = shape_to_np(shape)\n",
    "\t\t\n",
    "\t\t#simple hack ;)\n",
    "\t\tif (len(shape)==68):\n",
    "\t\t\t# extract the left and right eye (x, y)-coordinates\n",
    "\t\t\t(lStart, lEnd) = FACIAL_LANDMARKS_68_IDXS[\"left_eye\"]\n",
    "\t\t\t(rStart, rEnd) = FACIAL_LANDMARKS_68_IDXS[\"right_eye\"]\n",
    "\t\telse:\n",
    "\t\t\t(lStart, lEnd) = FACIAL_LANDMARKS_5_IDXS[\"left_eye\"]\n",
    "\t\t\t(rStart, rEnd) = FACIAL_LANDMARKS_5_IDXS[\"right_eye\"]\n",
    "\t\t\t\n",
    "\t\tleftEyePts = shape[lStart:lEnd]\n",
    "\t\trightEyePts = shape[rStart:rEnd]\n",
    "\n",
    "\t\t# compute the center of mass for each eye\n",
    "\t\tleftEyeCenter = leftEyePts.mean(axis=0).astype(\"int\")\n",
    "\t\trightEyeCenter = rightEyePts.mean(axis=0).astype(\"int\")\n",
    "\n",
    "\t\t# compute the angle between the eye centroids\n",
    "\t\tdY = rightEyeCenter[1] - leftEyeCenter[1]\n",
    "\t\tdX = rightEyeCenter[0] - leftEyeCenter[0]\n",
    "\t\tangle = np.degrees(np.arctan2(dY, dX)) - 180\n",
    "\n",
    "\t\t# compute the desired right eye x-coordinate based on the\n",
    "\t\t# desired x-coordinate of the left eye\n",
    "\t\tdesiredRightEyeX = 1.0 - self.desiredLeftEye[0]\n",
    "\n",
    "\t\t# determine the scale of the new resulting image by taking\n",
    "\t\t# the ratio of the distance between eyes in the *current*\n",
    "\t\t# image to the ratio of distance between eyes in the\n",
    "\t\t# *desired* image\n",
    "\t\tdist = np.sqrt((dX ** 2) + (dY ** 2))\n",
    "\t\tdesiredDist = (desiredRightEyeX - self.desiredLeftEye[0])\n",
    "\t\tdesiredDist *= self.desiredFaceWidth\n",
    "\t\tscale = desiredDist / dist\n",
    "\n",
    "\t\t# compute center (x, y)-coordinates (i.e., the median point)\n",
    "\t\t# between the two eyes in the input image\n",
    "\t\teyesCenter = (int((leftEyeCenter[0] + rightEyeCenter[0]) // 2),\n",
    "            int((leftEyeCenter[1] + rightEyeCenter[1]) // 2))\n",
    "\n",
    "\t\t# grab the rotation matrix for rotating and scaling the face\n",
    "\t\tM = cv2.getRotationMatrix2D(eyesCenter, angle, scale)\n",
    "\n",
    "\t\t# update the translation component of the matrix\n",
    "\t\ttX = self.desiredFaceWidth * 0.5\n",
    "\t\ttY = self.desiredFaceHeight * self.desiredLeftEye[1]\n",
    "\t\tM[0, 2] += (tX - eyesCenter[0])\n",
    "\t\tM[1, 2] += (tY - eyesCenter[1])\n",
    "\n",
    "\t\t# apply the affine transformation\n",
    "\t\t(w, h) = (self.desiredFaceWidth, self.desiredFaceHeight)\n",
    "\t\toutput = cv2.warpAffine(image, M, (w, h),\n",
    "\t\t\tflags=cv2.INTER_CUBIC)\n",
    "\n",
    "\t\t# return the aligned face\n",
    "\t\treturn output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f4660f08-ef48-44ec-aa63-6eb076ae7007",
   "metadata": {},
   "outputs": [],
   "source": [
    "landmark_name = \"shape_predictor_68_face_landmarks.dat\"\n",
    "if not os.path.isfile(landmark_name):\n",
    "    landmarks_url = \"https://github.com/italojs/facial-landmarks-recognition/raw/master/shape_predictor_68_face_landmarks.dat\"\n",
    "    out = requests.get(landmarks_url)\n",
    "    open(landmark_name, \"wb\").write(out.content)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "0cefabf1-60d0-4685-bba0-f376f99cda4d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Errno 2] No such file or directory: 'original_faces/IMG_0133.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/cfdc965cee-result-20210822214218..HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210112_233814.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20201101_092008.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20201221_105043.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210112_233814.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210325_165212.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210423_222337.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210502_173447.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210522_123528.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210614_183300.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210629_184214.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210804_182126.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210808_103300.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210821_150738.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210829_093342.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210814_171040.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210918_144126.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20211019_135415.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20211128_113632.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220102_120313.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220112_080748~2.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220217_084519.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220227_094625.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220301_222916.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220401_133508.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220409_201522.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220423_135319.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220522_105855.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220529_193704.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220626_135456.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220627_120122.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220704_121621.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220710_120555.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220728_130711.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20210313_152341.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220618_164453.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220626_133911.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220626_135456.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220627_120122.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220702_193708.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220704_121621.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220710_120555.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220728_130711.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220728_205915.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220811_183018.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220828_064758.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220829_123706.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220917_163316.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20220925_190928.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221013_190606.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221015_142308.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221019_094022.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221029_004046.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221115_083706.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221115_083810.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221120_182349.HEIC'\n",
      "[Errno 2] No such file or directory: 'original_faces/20221126_121051.HEIC'\n",
      "successful load of original_faces/IMG_0099.HEIC\n",
      "[Errno 2] No such file or directory: 'original_faces/IMG_0133.HEIC'\n",
      "successful load of original_faces/IMG_0219.HEIC\n",
      "successful load of original_faces/IMG_0220.HEIC\n",
      "successful load of original_faces/IMG_0327.HEIC\n",
      "successful load of original_faces/IMG_0331.HEIC\n",
      "successful load of original_faces/IMG_0373.HEIC\n",
      "successful load of original_faces/IMG_0519.HEIC\n",
      "successful load of original_faces/IMG_0548.HEIC\n",
      "successful load of original_faces/IMG_0561.HEIC\n",
      "successful load of original_faces/IMG_0615.HEIC\n",
      "successful load of original_faces/IMG_1779.HEIC\n",
      "successful load of original_faces/IMG_2190.HEIC\n",
      "successful load of original_faces/IMG_2191.HEIC\n",
      "successful load of original_faces/IMG_2324.HEIC\n",
      "successful load of original_faces/IMG_2352.HEIC\n",
      "successful load of original_faces/IMG_2584.HEIC\n",
      "successful load of original_faces/IMG_2713.HEIC\n",
      "successful load of original_faces/IMG_2745.HEIC\n",
      "successful load of original_faces/IMG_2902.HEIC\n",
      "successful load of original_faces/IMG_3007.HEIC\n",
      "successful load of original_faces/IMG_3033.HEIC\n",
      "successful load of original_faces/IMG_3084.HEIC\n",
      "successful load of original_faces/IMG_3185.HEIC\n",
      "successful load of original_faces/IMG_3312.HEIC\n",
      "successful load of original_faces/IMG_3351.HEIC\n"
     ]
    }
   ],
   "source": [
    "paths = glob('original_faces/*')\n",
    "failed_paths = []\n",
    "verbose = False\n",
    "save = True\n",
    "\n",
    "size = 1024\n",
    "\n",
    "detector = dlib.get_frontal_face_detector()\n",
    "predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')\n",
    "fa = FaceAligner(predictor, desiredFaceWidth=size, desiredLeftEye=(.42,.5))\n",
    "\n",
    "def to_aligned_path(image_path):\n",
    "    aligned_base = f'aligned_faces/{os.path.basename(image_path)}'\n",
    "    aligned_path =  os.path.splitext(aligned_base)[0] + '.jpg'\n",
    "    return aligned_path\n",
    "\n",
    "for image_path in paths:\n",
    "    aligned_path = to_aligned_path(image_path)\n",
    "    if os.path.isfile(aligned_path) or  os.path.basename(image_path) in image_issues:\n",
    "        continue\n",
    "    try:\n",
    "        # load the input image, resize it, and convert it to grayscale\n",
    "        # load and transform image\n",
    "        image = Image.open(image_path).convert('RGB')\n",
    "        image = ImageOps.exif_transpose(image)\n",
    "        image = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)\n",
    "        image = imutils.resize(image, width=800)\n",
    "        print(f'successful load of {image_path}')\n",
    "        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\n",
    "        # show the original input image and detect faces in the grayscale\n",
    "        # image\n",
    "        cv2.imshow(\"Input\", image)\n",
    "        rects = detector(gray, 2)\n",
    "\n",
    "\n",
    "\n",
    "        # loop over the face detections\n",
    "        rect = rects[0]\n",
    "        # extract the ROI of the *original* face, then align the face\n",
    "        # using facial landmarks\n",
    "        (x, y, w, h) = rect_to_bb(rect)\n",
    "        faceOrig = imutils.resize(image[y:y + h, x:x + w], width=size)\n",
    "        faceAligned = fa.align(image, gray, rect)\n",
    "        if save:\n",
    "            cv2.imwrite(aligned_path, faceAligned)\n",
    "        # display the output images\n",
    "        if verbose:\n",
    "            plt.subplot(1,2,1)\n",
    "            plt.imshow(faceOrig)\n",
    "            plt.subplot(1,2,2)\n",
    "            plt.imshow(faceAligned)\n",
    "            plt.show()\n",
    "    except Exception as e:\n",
    "        print(e)\n",
    "        failed_paths.append(image_path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "id": "a84d3268",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_date_taken(path):\n",
    "    exif = Image.open(path).getexif()\n",
    "    if not exif:\n",
    "        print('Image {0} does not have EXIF data.'.format(path))\n",
    "        return None\n",
    "    return exif.get(306)\n",
    "\n",
    "dates = []\n",
    "for path in paths:\n",
    "    if os.path.basename(path) in image_issues:\n",
    "        continue\n",
    "    date = get_date_taken(path)\n",
    "    if date is not None:\n",
    "        dates.append((date, to_aligned_path(path)))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "id": "f58a906c-9f95-420c-9a1b-8ebadd13a481",
   "metadata": {},
   "outputs": [],
   "source": [
    "images = [i[1] for i in sorted(dates, key = lambda x: x[0])]\n",
    "frame = cv2.imread(images[0])\n",
    "height, width, layers = frame.shape\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "id": "6da84bbb-e20a-4eed-aca0-9f99e989c9e0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'\n",
      "OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'\n",
      "[ WARN:0@2705.058] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/DSC_0492.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2705.803] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20201031_184422.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.232] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210111_152931.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.232] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210116_142229.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.345] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210206_103216.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.506] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210306_113702.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.659] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210322_174406.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.698] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210328_091958.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.755] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210403_095353.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.854] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210406_200042.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2706.954] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210411_114610.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2707.388] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210429_112816.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2707.415] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210501_172013.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2707.616] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210511_143942(1).jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2707.830] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210522_144933.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.011] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210613_184202.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.221] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210722_094401.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.388] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210903_145440.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.436] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20210913_204003.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.825] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211031_194113.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.866] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211120_184312.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.866] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211120_193412.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.984] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211201_101824.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2708.984] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211204_215005.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.075] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211229_050057.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.116] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211231_102941.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.116] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211231_103547.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.116] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20211231_103553.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.255] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220113_190010.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.449] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220129_100140.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.449] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220130_091257.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.580] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220213_143835.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2709.719] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220226_100421.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2710.119] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220423_215050.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2710.221] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220521_090409.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2710.418] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220527_200104.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2710.433] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220528_172240.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2710.558] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220601_123402.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.132] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220730_114002.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.214] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220805_202813.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.438] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220828_153523.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.704] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220902_225019.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.704] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220903_011359.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.704] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220903_025108.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.704] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220903_162718.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2711.722] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220903_181114.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2712.189] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20220930_222330.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2712.979] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/20221125_103934.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2713.410] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/IMG_0210.jpg'): can't open/read file: check file path/integrity\n",
      "[ WARN:0@2715.263] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('aligned_faces/IMG_2279.jpg'): can't open/read file: check file path/integrity\n"
     ]
    }
   ],
   "source": [
    "output_filename = 'aligned_faces_video.mp4'\n",
    "fps = 9\n",
    "fourcc = cv2.VideoWriter_fourcc(*'MP4V')\n",
    "video = cv2.VideoWriter(output_filename, fourcc, fps, (width,height))\n",
    "for image in images:\n",
    "    video.write(cv2.imread(image))\n",
    "\n",
    "cv2.destroyAllWindows()\n",
    "video.release()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
